### ISSUE TITLE
add flags to point to build/check output files?

### ISSUE THREAD

**Issue by dtenenba** [Bioconductor/BiocCheck#10]
A lot can be learned from the output of `R CMD build` and `R CMD check`; for example, whether the vignette is built, whether unit tests are run, and so on. In the context of the single package builder, the output of these commands is readily available so we could pass the filenames to `BiocCheck` so that it could do additional checks. The .Rcheck directory is also available....

**Comment by lshep** [comment]
Nice idea!  Don't think we will be implementing any changes on this in the near future beyond what is already printed for the SPB output in build report.
