### ISSUE TITLE
BiocCheck space indentation in Rmakrdown vignette documents

### ISSUE THREAD

**Issue by harpomaxx** [Bioconductor/BiocCheck#100]
A possible incompatibility problem seems to exist between the indentation required for yaml syntax in the author section of Rmarkdown documents and BiocCheck multiple of 4 space recommendation.  If the author section has several authors, affiliations, and emails it is not possible to use multiple of 4 space indentation without breaking the vignette construction process.
 
 In section[ 3.1 of the biocstyle vignette about authoring using Rmarkdown ](https://www.bioconductor.org/packages/release/bioc/vignettes/BiocStyle/inst/doc/AuthoringRmdVignettes.html),  The author and affiliation sections use just 2 spaces instead of the recommended multiple of 4. Using such yaml example as-is produce a BiocCheck NOTE.

Using BiocCheck 1.25.3.
R 4.0.0

**Comment by mtmorgan** [comment]
yes; I recommend that you simply ignore this NOTE. The spirit of BiocCheck is to move package code toward 'best practice', so some false positives are tolerated.

If you'd like to submit a pull request, the idea would be to disable the check in the yaml part of an Rmd file, modifying this function https://github.com/Bioconductor/BiocCheck/blob/c0d2faa6b5fac1c812bfa3e5d45ea09b322254b0/R/checks.R#L1432 ini some way.
