### ISSUE TITLE
BiocCheck should allow versions x.99.z, for x other than 0

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocCheck#101]
Currently
```
* Checking new package version number...
    * ERROR: New package version starting with 0.99.* (e.g., 0.99.0,
      0.99.1, ...); got 2.99.1.
```
but since the package has already been released through other channels as 2.5.z, it seems like the right thing to do is to use version 2.99.0 for a new '3.0.0' release in Bioconductor. The check should be a warning or perhaps note, or at least point to a discussion in the vignette.

**Comment by lshep** [comment]
I think the majority of packages we want to have come in at 0.99.0  with the exception if it has already been released and utilized under the higher version 1.0.0  etc and we would still want to have 1.99.z or 2.99.z  indicating a x version bump when officially released in Bioconductor ... I will update to a warning and clarify the message, and add or update a section in the vignette with more detail.   
Cheers
