### ISSUE TITLE
pull request template currently provides little additional value

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocCheck#108]
The BiocCheck [pull request template](https://github.com/Bioconductor/BiocCheck/blob/master/.github/pull_request_template.md) seems to produce a pull request **WITH A LOT OF SHOUTING** and not much added value at the top (e.g., https://github.com/Bioconductor/BiocCheck/pull/105; https://github.com/Bioconductor/BiocCheck/pull/107) can it be simplified @lcolladotor ?

**Comment by mtmorgan** [comment]
@lcolladotor can you provide a screenshot or ... that illustrates what a pull request under your revision will look like? For instance there is a reference to 'currently' and 'May', which doesn't seem correct...

**Comment by lcolladotor** [comment]
Well, the PR removes the YAML lines that add the black bolded text that you found of no real value **. So it only leaves the lines like

![image](https://user-images.githubusercontent.com/2288213/96776993-bb76cc80-13b7-11eb-9773-77b42a8a83f7.png)

taken from https://github.com/Bioconductor/BiocCheck/pull/105. To provide a true screenshot, I would need to fork my already existing fork a second time, then send a PR to my fork.


** It looks like the commit message is added before the YAML code, and that somehow breaks it. So yeah, I think that removing all the YAML is a good solution.

**Comment by mtmorgan** [comment]
And the mention of May, 2020? Is that necessary / useful?

**Comment by lcolladotor** [comment]
Ahh, you want to further edit the text? I only thought you wanted to drop all the bold font. 

Sure, let me add a small commit to the PR to delete `(currently in May 2020 that would be Bioconductor 3.12)`.
