### ISSUE TITLE
Error in checking man page documentation

### ISSUE THREAD

**Issue by Jiefei-Wang** [Bioconductor/BiocCheck#120]
Hi,

Here is a (possibly) simple error I got when I was running `BiocCheck::BiocCheck()`
```
* Checking man page documentation...
    * ERROR: At least 80% of man pages documenting exported objects must have
      runnable examples. The following pages do not:
Error in sprintf(...) : 'fmt' length exceeds maximal format length 8192
```
It looks like there is a length restriction on `sprintf`. Since I have over 500 functions without examples, it hits this uncommon limit. The BiocCheck version I'm using is `1.27.2` and here is my R session

```
R Under development (unstable) (2020-09-03 r79126)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)
```

Cheers,
Jiefei

**Comment by lshep** [comment]
huh... well that's good to know ....

**Comment by mtmorgan** [comment]
Probably one would like to print the first 6 and say 'and xxx other pages'

**Comment by hpages** [comment]
Also `sprintf()` is used indiscriminately here even when there is nothing to format:
```
> BiocCheck:::.msg
function (..., appendLF = TRUE, indent = 0, exdent = 2) 
{
    txt <- sprintf(...)
    message(paste(strwrap(txt, indent = indent, exdent = exdent), 
        collapse = "\n"), appendLF = appendLF)
}
```
If `BiocCheck:::.msg()` receives a single argument via `...`, then there is nothing to format so you can skip the call to `sprintf()`.

**Comment by LiNk-NY** [comment]
Should be resolved in https://github.com/Bioconductor/BiocCheck/commit/a3118735b080794e9b7e911cc75214ec6e63301a
