### ISSUE TITLE
arguments passed to `...` ignored in BiocCheck.

### ISSUE THREAD

**Issue by aljabadi** [Bioconductor/BiocCheck#130]
Trying BiocCheck('.', \`--no-check-dependencies\` = TRUE, \`--no-check-vignettes\` = TRUE) interactively I noticed that the dependencies checks are still performed. The apparent problem seems to arise from the fact that args are passed in backticks but the `BiocCheck` function check for `dot[["$(arg-without-backtick)"]]`. Using dots$\`arg\` seems to rectify the issue but not sure if it will have side-effects.

**Comment by lshep** [comment]
Perhaps the documentation needs to be updated? Where did you see the use of the `--`  You can use the different flags by specif icing like so: 
```
 BiocCheck("BiocFileCache/", `no-check-bioc-help`=FALSE, `no-check-dependencies`=TRUE, `no-check-vignettes` = TRUE)
```

**Comment by aljabadi** [comment]
That's correct. I used the wrong format for flags, thanks.
