### ISSUE TITLE
install / install.packages

### ISSUE THREAD

**Issue by lshep** [Bioconductor/BiocCheck#134]
I thought we implemented a check that would flag if install or install.packages was utilized.  I had a package that used it in the vignette code but was not picked up by the check.   Packages should never install packages for users.

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 
I think we check this in the R code but not in vignettes. I will take a look.

**Comment by LiNk-NY** [comment]
If there are any calls you come across that are not being caught, feel free to re-open.
