### ISSUE TITLE
bulletproofing related to "watched tags" and email checking

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/BiocCheck#135]
This relates to https://support.bioconductor.org/p/9136638/

for which Mike Smith gave the following insight:

The Error in `strsplit(content(response)$watched_tags, split = ",") : non-character argument Calls: BiocCheck ... is.factor -> mysub -> sub -> is.factor -> unlist -> strsplit Execution halted` part looks more like a problem with BiocCheck itself. It's trying to makes sure that you've added the name of the package you're checking to the "watched tags" in your profile, but that isn't working correctly for some reason. It's probably good to make sure you've done that (that might even fix it) but it doesn't look to me like the actual error is your problem.

Right around https://github.com/Bioconductor/BiocCheck/blob/fa35fc7b70eb48e1aea04cc6cb618505e8a2d4de/R/checks.R#L1813
I think we need to look at the content of the API call to see if the response is any good so strsplit doesn't get to fail and message the user.

Also at https://github.com/Bioconductor/BiocCheck/blob/fa35fc7b70eb48e1aea04cc6cb618505e8a2d4de/R/checks.R#L1786
we ran into a case where mismatch in case (S vs s) between Maintainer email in DESCRIPTION and maintainer email on git credentials data threw a similarly obscure error ... but I don't have the transcript.  Again I think we have to look at the content of API response carefully to make sure we have something usable and not let a base R function do the failure.  I will try to get a transcript.

This relates to adding test cases on a range of positive and negative "controls" for getting utilities like this into an error state and ensuring we give the user information that will help them solve the problem.

**Comment by lshep** [comment]
I had tested it with a valid email and invalid email and with a blank field and with a response.  

If I remember correctly some emails are case sensitive and some are not depending on email host so its not like we could change the emails in the database for the support site to match and similar with the git creds app.

**Comment by lshep** [comment]
But I'll investigate this and see if I can track down why the strsplit is failing -- if anything then there should be a check for a valid entry when entering on the support site and not necessarily a change to the check here in my opinion

**Comment by vjcitn** [comment]
These are not urgent.  The case-sensitivity seems something the user has to deal with in DESCRIPTION but if the error messages can direct them to this it is a win.

**Comment by lshep** [comment]
case-sensitivity is something the user will have to deal with in all of R.   But yes a more informative message would be good

**Comment by lshep** [comment]
@vjcitn  @Natay    Okay.  traced it back.   The API email check is not case sensitive so when BiocCheck does the verification using the core team email it deems both  bioconductorcoreteam@gmail.com  and  bioconductorcoreTeam@gmail.com as the same valid email.   However the api check for the watched tags is case-sensitive --  so the valid email produces an empty watched tags 
```
{
    "watched_tags": ""
}
``` 
While the invalid email produces an empty list
```
{}
```
Since R and the emails should probably be case sensitive is there a way to make the API email check case sensitive or do you think there is a better solution ?

**Comment by lshep** [comment]
I could change the watched tags list to catch the later case -- but not sure which is better

**Comment by Natay** [comment]
We can fix it on the api side but email checks should be case sensitive since the watched tags are as well ( we can also make both case insensitive ), either way  we will return a 404 response for invalid emails.
BiocCheck can validate the status_code to check for errors.

**Comment by lshep** [comment]
yes I think if the git api and R is all case sensitive than we would probably want case sensitive as well --  I opened the issue that is linked above.  Keep me posted and when it is implemented I will have updated tests and checks in the BiocCheck code.

**Comment by vjcitn** [comment]
@Natay thanks -- i agree that BiocCheck needs to process the status_code.  I think it should be possible for BiocCheck to tell the BiocCheck user what has gone wrong and make a suggestion.

**Comment by LiNk-NY** [comment]
Fixed in RELEASE_3_18 cfc873410c42d360895e01be09662aec2eab5840
