### ISSUE TITLE
Vignettes should always be checked regardless of package type

### ISSUE THREAD

**Issue by lshep** [Bioconductor/BiocCheck#136]
In a package I'm reviewing the vignette checks seemed to be skipped 
And the formatting seems to be off with regard to .Rbuildignore check addition? 

```

* Checking License: for restrictive use...
* Checking DESCRIPTION/NAMESPACE consistency...
* Checking .Rbuildignore...
    This is not a software package, skipping vignette checks...
* Checking library calls...
* Checking for library/require of BioImageDbs...
* Checking coding practice...
```

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 

It looks like it is a bug in `Checking vignette directory...`: 

https://github.com/Bioconductor/BiocCheck/blob/fa35fc7b70eb48e1aea04cc6cb618505e8a2d4de/R/BiocCheck.R#L231-L233

The `handleCheck("Checking vignette directory...")`  line should be outside of the conditional. I can fix this. 

Best,
Marcel

**Comment by lshep** [comment]
Thanks!

**Comment by lshep** [comment]
I think we want to check all packages for a vignette right?    Now that I think about it I changed the code so that infrastructure packages have to have vignette and not necessarily this case where its a non software.

**Comment by LiNk-NY** [comment]
Yes, data packages should have minimal vignettes showing how to pull down the data at least...
