### ISSUE TITLE
Integrate "available" to check for "valid" package names

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/BiocCheck#140]
Would be nice to integrate the [available](https://github.com/r-lib/available) package as an additional check to `BiocCheck` to check against *problematic* package names.

**Comment by LiNk-NY** [comment]
I created an `avail` branch for testing. 
https://github.com/Bioconductor/BiocCheck/tree/avail/
It's still a work in progress but the output looks a bit unwieldy. 
I may decide to drop the functionality if the output does not look
amenable to `BiocCheck`'s style of output.
