### ISSUE TITLE
Set all Renviron.bioc env variables

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/BiocCheck#142]
with option to unset.  these should all be set by default for the BiocCheck run to maximize sensitivity

https://bioconductor.org/checkResults/3.14/bioc-LATEST/Renviron.bioc

**Comment by hpages** [comment]
Most importantly I think that we want to set these variables when running `R CMD build` and `R CMD check` on the SPB. Setting them when running **BiocCheck** wouldn't achieve that. In other words, this is an SPB issue, not a BiocCheck one.

**Comment by lshep** [comment]
The SPB list the file of all the variables set for it and advertises it on the repo  
https://github.com/Bioconductor/Contributions#r-cmd-check-environment

**Comment by LiNk-NY** [comment]
I think this refers to the errors that were observed in https://github.com/Bioconductor/BiocCheck/pull/141 
Setting these env variables during `BiocCheck` would not add as much
(checking these only for the code that is run in BiocCheck) as when running `R CMD check`
as Hervé pointed out.
It doesn't hurt to add a note about these environment variables in the output so to increase awareness
among community members.

**Comment by LiNk-NY** [comment]
I think it is currently out of the scope of the package. Re-open if you feel otherwise. Thanks.
