### ISSUE TITLE
`there is no package called ‘build’`

### ISSUE THREAD

**Issue by bschilder** [Bioconductor/BiocCheck#144]
When running `BiocCheck::BiocCheck()` within  the current Bioconductor docker container (currently v3.14), I get the following error:
```
there is no package called ‘build’
```
See the [GHA workflow report here](https://github.com/neurogenomics/orthogene/runs/4048982495?check_suite_focus=true#step:6:4995). 

In [this container](https://hub.docker.com/layers/bioconductor/bioconductor_docker/latest/images/sha256-d274974ec781ce48642f8cb804b0da66b475f221d3587d7cd4d29542fbb29404?context=explore), it is using `BiocCheck` v1.30.0 (the current version on Bioconductor v3.14) and R v4.1.1.

What's odd is that I can't seem to find any R package named "build" (on CRAN or Bioc). Do you know what might be going on here?

Many thanks, 
Brian

**Comment by LiNk-NY** [comment]
Hi Brian, @bschilder 
This depends on the setup you are using. 
Make sure that the `getwd()` is at the base package directory in order to run `BiocCheck::BiocCheck()`, otherwise you would have to call it as `BiocCheck::BiocCheck("packagename")` if you are one directory below the package directory. 
Best,
Marcel

**Comment by bschilder** [comment]
Thanks for the quick reply @LiNk-NY.

Here is the workflow that I used. You can see that the package I'm building/testing (in this case `orthogene`) is first checked out from GitHub.
https://github.com/neurogenomics/orthogene/blob/b9cb5a8d9212e648a0ef1303680ac598eae3dccb/.github/workflows/dockerhub.yml

Here is the Dockerfile that was run. Within this file, the checked out package is  then copied to the subfolder `build_zone` which is made the working directory. I can confirm this same workflow was working yesterday, so I can't quite figure out why the "build" error appeared today.
https://github.com/neurogenomics/orthogene/blob/b9cb5a8d9212e648a0ef1303680ac598eae3dccb/Dockerfile

The "latest" version of the Bioc Docker container was "devel' at the time I ran it (it was updated just 2 hours ago).
https://hub.docker.com/layers/bioconductor/bioconductor_docker/latest/images/sha256-d274974ec781ce48642f8cb804b0da66b475f221d3587d7cd4d29542fbb29404?context=explore

**Comment by LiNk-NY** [comment]
Hi Brian, 

Sorry, this is not really a `BiocCheck` issue but more of a set up issue. 
The package will run if you run this locally. 

I can recommend that you use the `biocthis` to set up the check instead.

Best regards,
Marcel

**Comment by bschilder** [comment]
> Sorry, this is not really a BiocCheck issue but more of a set up issue. The package will run if you run this locally.

Possibly, but I do want to first make sure `BiocCheck` isn't failing due to some unstated dependencies (R packages or Linux). 

> I can recommend that you use the biocthis to set up the check instead.

`biocthis` is a great place to start; I actually based my workflows off of this with some modifications to improve flexibility (i.e. not hard-coding bioc/R versions and package names). However they don't provide templates for Dockerfiles, which is the main issue here.

**Comment by bschilder** [comment]
# Update

The issue `there is no package called ‘build’` error produced by `BiocCheck` persists in the devel version (v3.15) of the official Bioconductor docker container .

https://github.com/neurogenomics/orthogene/runs/4069981383?check_suite_focus=true

**Comment by LiNk-NY** [comment]
Hi Brian, 

Please provide a [minimally reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) where `BiocCheck` is shown to fail with this error.

Otherwise, you are responsible for debugging the GHA environment / customized script being used.

Best regards,
Marcel

**Comment by bschilder** [comment]
# Issue

`BiocCheck` sometimes produces the error `there is no package called ‘build’`.

# reprex

> Please provide a minimally reproducible example where BiocCheck is shown to fail with this error.

## reprex 1  

Fork the repo in the [the original reprex](https://github.com/Bioconductor/BiocCheck/issues/144#issue-1039759378)  and make a push.

## reprex 2

Alternatively, you could copy and paste the [GHA workflow code provided in the original reprex ](https://github.com/neurogenomics/orthogene/blob/b9cb5a8d9212e648a0ef1303680ac598eae3dccb/.github/workflows/dockerhub.yml) into any bioconductor project and reproduce the error. 

## reprex 3

Here is a third way to reproduce the `BiocCheck` error.

```
### create biodocker image 
docker pull bioconductor/bioconductor_docker:devel
docker exec -it <image_id> /bin/sh
### Install Linux deps
apt-get update && \
    apt-get install -y \
    git-core \
    libcurl4-openssl-dev \
    libgit2-dev \
    libicu-dev \
    libssl-dev \
    make pandoc \
    pandoc-citeproc \
    zlib1g-dev \
	## Additional resources
	xfonts-100dpi \
	xfonts-75dpi \
	biber \
	libsbml5-dev \
	## qpdf needed to stop R CMD Check warning
	qpdf \
	&& apt-get clean \
    && rm -rf /var/lib/apt/lists/*

### Clone any bioc package's GH repo. We will use orthogene as an example here.
git clone https://github.com/neurogenomics/orthogene.git
mkdir build_zone
scp -r orthogene/* build_zone/
cd build_zone

### Install R dependencies
Rscript -e 'options(download.file.method= "libcurl"); 
                if(!"BiocManager" %in% rownames(utils::installed.packages)) install.packages("BiocManager");  
                bioc_ver <- BiocManager::version(); 
                options(repos = c(BiocManager::repositories(),
                                  AnVIL = file.path("https://bioconductordocker.blob.core.windows.net/packages",bioc_ver,"bioc"),
                                  CRAN = "https://cran.rstudio.com/"),
                                  download.file.method = "libcurl", Ncpus = 2); 
                BiocManager::install("AnVIL", ask = FALSE);                                   
                AnVIL::install(c("remotes","devtools","desc")); 
                try({remotes::install_github("bergant/rapiclient")}); 
                deps <- remotes::dev_package_deps(dependencies = TRUE)$package; 
                AnVIL::install(pkgs = deps,  ask = FALSE); 
                deps_left <- deps[!deps %in% rownames(installed.packages())]; 
                if(length(deps_left)>0) devtools::install_dev_deps(dependencies = TRUE, upgrade = "never");'

# Run R CMD check - will fail with any errors or warnings
Run Rscript -e 'devtools::check()' 

# Run Bioconductor's BiocCheck 
Rscript -e 'if(!"BiocCheck" %in% rownames(utils::installed.packages)) AnVIL::install("BiocCheck", quiet = TRUE);
                BiocCheck::BiocCheck()'
```

# Source of error

Upon digging into `BiocCheck`'s code, I found the source of the error:
https://github.com/Bioconductor/BiocCheck/blob/49a2ad3c3c85eaaf36f34fb359179fcbaaa59085/R/BiocCheck.R#L321

```
.get_package_name <- function(input)
{
    strsplit(basename(input), "_")[[1]][1]
}
```

It looks like `BiocCheck` currently makes some assumptions about the folder structure of R package; i.e. that the folder name will always correspond to package name exactly. This is often, but not always, the case. For example:  

1. The GitHub repo name contains an "_", but the R package name replaces this with a "." due to R package naming constraints (e.g. [`MAGMA_Celltyping`](https://github.com/neurogenomics/MAGMA_Celltyping)).  
2. The contents of the R project is copied into another temporary folder before building/running checks, e.g. *build_zone*.  

# Solution

A more robust way to get the package info would be from the DESCRIPTION file, which will always contain the exact package name and is a requirement for every R package (whereas GitHub folder structure is not).

```
install.packages("desc")
...
...
.get_package_name <- function(input)
{
    desc::desc_get_field(key = "Package")
}
```

I will make a Pull Request with this fix. Feel free to improve upon this further.

In the meantime, could you please reopen this issue until this issue is resolved? 

Many thanks, 
Brian

**Comment by mtmorgan** [comment]
Does `desc::desc_get_field()` provide advantages (relevant in the context of `.get_package_name()`) over `read.dcf("DESCRIPTION", fields = "Package")[[1]]`?

FWIW a simpler reproducible example is

```
wd <- tempfile(); dir.create(wd)
setwd(wd)
x = 1
package.skeleton("build", "x")
file.rename("build", "build_zone")
BiocCheck::BiocCheck("build_zone")
```

**Comment by bschilder** [comment]
@mtmorgan I hadn't heard of `read.dcf`, but not requiring the `desc` dep would be great! I'll try implementing that instead in my PR. Thanks for the helpful tip.

**Comment by LiNk-NY** [comment]
Thanks Brian, 
We've made discovering the package name more robust. See the change in 9f72c38. 
Best,
Marcel

**Comment by bschilder** [comment]
@LiNk-NY thanks for implementing this quickly. 

Did you try rerunning the reprex above?
Both [mine](https://github.com/Bioconductor/BiocCheck/issues/144#issuecomment-956549110) and [that of](https://github.com/Bioconductor/BiocCheck/issues/144#issuecomment-956565328) @mtmorgan  still seem to produce the same error as before.

I made sure to upgrade first (as well as reset my R session): 

```R
remotes::install_github("Bioconductor/BiocCheck", upgrade = "always", force = TRUE);
packageVersion("BiocCheck")
```
```
[1] ‘1.31.6’
```

Looking into the most recent code, looks like there's still a number of places where the package name is still inferred from the folder name. 
https://github.com/Bioconductor/BiocCheck/search?q=strsplit

Could you try doing another sweep through the code and running the reprex to confirm it's behaving as expected? You may want to consider adding some tests for this.

Thanks, 
Brian

# Session info

<details> 

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] graph_1.72.0        rstudioapi_0.13     knitr_1.36          BiocGenerics_0.40.0
 [5] BiocCheck_1.31.6    getopt_1.20.3       R6_2.5.1            httr_1.4.2         
 [9] tools_4.1.0         biocViews_1.62.0    parallel_4.1.0      pkgbuild_1.2.0     
[13] Biobase_2.54.0      xfun_0.27           cli_3.1.0           withr_2.4.2        
[17] remotes_2.4.1       RBGL_1.70.0         rprojroot_2.0.2     optparse_1.7.1     
[21] crayon_1.4.2        processx_3.5.2      BiocManager_1.30.16 callr_3.7.0        
[25] codetools_0.2-18    bitops_1.0-7        ps_1.6.0            stringdist_0.9.8   
[29] RCurl_1.98-1.5      RUnit_0.4.32        curl_4.3.2          compiler_4.1.0     
[33] prettyunits_1.1.1   stats4_4.1.0        XML_3.99-0.8   
```

</details>

**Comment by bschilder** [comment]
# Update

It appears some additional changes were made since my previous post.

## Persisting error 

I just tested this newest version of `BiocCheck` (1.31.9) with @mtmorgan's [reprex](https://github.com/Bioconductor/BiocCheck/issues/144#issuecomment-956565328) and they still appear to be failing with the original error message. 

Were the unit tests implemented? @LiNk-NY 

## New `BiocCheck` behaviour

When running [reprex 3 above](https://github.com/Bioconductor/BiocCheck/issues/144#issuecomment-956549110), a new error is produced, which appears to be a new addition to `BiocCheck`.

```
* Checking that Package field matches directory/tarball name...
    * ERROR: Package directory 'buildzone' must match Package: field
      (got 'orthogene').
```

If it hasn't been already, perhaps this change to `BiocCheck`'s behaviour should be documented somewhere?

## Docker: best practices 

Copying the contents of an R package to another folder is best practice for building Docker containers, since it avoids including additional files that can inflate the size of the resulting Docker image. 

Should `BiocCheck` be avoided when trying to use Docker containers (from Bioconductor or otherwise)? Would love to use both together!

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

Best, 
Brian

**Comment by LiNk-NY** [comment]
Hi Brian, @bschilder 

This has been documented in the vignette. See the [Build System Compatibility Checks](https://bioconductor.org/packages/devel/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#build-system-compatibility-checks). 

> Should BiocCheck be avoided when trying to use Docker containers

No, you shouldn't avoid `BiocCheck` and it comes down to how the set up is handled. 
It's probably a good idea to copy the package directory over to the container and
run the check within the folder. 

Best,
Marcel

**Comment by bschilder** [comment]
> This has been documented in the vignette. See the [Build System Compatibility Checks](https://bioconductor.org/packages/devel/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#build-system-compatibility-checks).

Great! Thanks for adding the link here. Just wanted to make sure users know the outcome of this if they encounter similar error messages in the future. I think if they read only up to the point where the issue was marked as resolved they might mistakenly think that `BiocCheck` now only relies on the DESCRIPTION file for deriving the package name (instead of the working directory name), and allows differences between working directory name and package name.
 
> 1. The GitHub repo name contains an "_", but the R package name replaces this with a "." due to R package naming constraints (e.g. MAGMA_Celltyping).
> 2. The contents of the R project is copied into another temporary folder before building/running checks, e.g. build_zone.

So in the first scenario [I posed here](https://github.com/Bioconductor/BiocCheck/issues/144#issuecomment-956549110), I suppose the recommendation that `BiocCheck` would make it to either 1) change the GitHub repository name, or 2) change the R package's name.

> No, you shouldn't avoid `BiocCheck` and it comes down to how the set up is handled. It's probably a good idea to copy the package directory over to the container and run the check within the folder.

Ok, I'll see if I can come up with a roundabout solution.

**Comment by LiNk-NY** [comment]
I've changed the code where the tarball / directory was being used to infer the package name and added code to check the `DESCRIPTION` file within the tarball / directory. So it should only rely on the `DESCRIPTION` file to get the package name. 

Your current setup triggers a separate check where the package directory does not match the package name as found in the `DESCRIPTION` field. This can be resolved by running the check on the tarball. 

Best,
Marcel
