### ISSUE TITLE
BiocCheck version number check

### ISSUE THREAD

**Issue by lshep** [Bioconductor/BiocCheck#146]
They are right.  It does not show. 
https://github.com/Bioconductor/Contributions/issues/2430

Should the version number checks be on by default?

**Comment by LiNk-NY** [comment]
Thanks. Perhaps we should have a `--new-submission` flag/option?
The check would include version number and support site registration for starters.

**Comment by lshep** [comment]
It should already have that built in.  But I think its off by default

**Comment by LiNk-NY** [comment]
Ah I see it now. Perhaps the recommendation in the comment should be to run
``BiocCheck::BiocCheck(`new-package` = TRUE)`` so that others who are using `BiocCheck`
with GHA don't get the new package checks by default.

**Comment by lshep** [comment]
could do that too.  And also update the contributions.bioconductor.org instructions for submitting packages for this too.

**Comment by lshep** [comment]
I can update the comments produced by the issue bot.

**Comment by LiNk-NY** [comment]
I've also moved the bioc-devel and support site subscription checks to the new-package checks.

**Comment by lshep** [comment]
I don't think they should just be for new packages -- its important that any maintainer is on the bioc-devel and support site -- if maintainers have changed emails or something its good to report

**Comment by LiNk-NY** [comment]
Sounds good. I will change it back or create a new check with wording more relevant to current maintainers.

**Comment by LiNk-NY** [comment]
I've reverted the change. Thanks. Closing the issue.
