### ISSUE TITLE
BiocCheck 1.31.29 is not finding the dependencies when you have multiple libraries (libPaths)

### ISSUE THREAD

**Issue by lcolladotor** [Bioconductor/BiocCheck#148]
Hi @LiNk-NY,

I'm running into an issue with `BiocCheck` version 1.31.29 where it fails to install a package, like at https://github.com/LieberInstitute/spatialLIBD/runs/4956510109?check_suite_focus=true#step:25:27. I think that it's because it's only finding one of the multiple libraries where packages are installed which you can see at https://github.com/LieberInstitute/spatialLIBD/runs/4956510109?check_suite_focus=true#step:21:298 (in this case there are 3 of them). For example, the error message complains that `SpatialExperiment` is absent, but you can find it at https://github.com/LieberInstitute/spatialLIBD/runs/4956510109?check_suite_focus=true#step:21:258.

Checking recent commits, it seems like maybe you addressed this already 2 hours ago at https://github.com/Bioconductor/BiocCheck/commit/49af29dc08fb057ad62cc4065512c70555a96682 (in a commit newer than version 1.31.29). Is that right?

Best,
Leo

**Comment by LiNk-NY** [comment]
Hi Leo! @lcolladotor 
Yes, thanks for catching this. That change should fix the issue.
It slipped through the cracks :)
Best,
Marcel

**Comment by lcolladotor** [comment]
Ahh, no worries! I tested it at https://github.com/LieberInstitute/spatialLIBD/commit/f3e7bfeac65df51fc3bdaf37e3e3507ffc7cd749 (and well https://github.com/LieberInstitute/spatialLIBD/commit/f9591c700e0bb8cd8a873ac5a70b9bd0807dd2d9) and it works again ^^ as you can see at https://github.com/LieberInstitute/spatialLIBD/runs/4957640979?check_suite_focus=true#step:25:1.

Thanks again Marcel!
