### ISSUE TITLE
too many reports of = for assignment

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/BiocCheck#149]
http://bioconductor.org/spb_reports/LinTInd_buildreport_20220111081005.html

Search for `Avoid using`

could this be compacted?   Seems like any of the `Avoid` events could have a count of events and some example line numbers but does not need to be exhaustive.

**Comment by LiNk-NY** [comment]
This issue is systemic to the way the code is written (with `for` loops) and there is no easy way to reduce the number of reports outside of doing it for this single instance (`=`) though other checks will remain unaffected. A fix is readily possible on the `output` branch.

**Comment by LiNk-NY** [comment]
closed in 16cf48c667858f9ce7dadefe8f69140c9efcfd91
