### ISSUE TITLE
Check vignette title

### ISSUE THREAD

**Issue by nuno-agostinho** [Bioconductor/BiocCheck#15]
BiocCheck should confirm the vignette title. For instance, I copied the vignette header from a [template](https://www.bioconductor.org/packages/devel/bioc/vignettes/BiocStyle/inst/doc/HtmlStyle.html) and I did not notice that the vignette title was set with the line `%\VignetteIndexEntry{Vignette Title}`.

I have seen other packages with such titles and I'm sure there are more people like me that thought the name of the vignette would be retrieved from `title` instead. Maybe this could print a warning or, at least, a note?

**Comment by lshep** [comment]
Checked in version >= 1.15.6
