### ISSUE TITLE
`cat()` is appropriate inside S3 print methods

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocCheck#150]
BiocCheck generates the following note

```
    * NOTE: Avoid 'cat' and 'print' outside of 'show' methods
      Found in files:
        cat() in R/db.R (line 79, column 5)
```
from https://github.com/mtmorgan/cellxgenedp/blob/3f9a195160faa22cb0e48469b470f22c78925df8/R/db.R#L76-L87, but `cat()` is appropriate in this S3 print method.

**Comment by LiNk-NY** [comment]
Closed in 727dad4a47e8382debf2f36cdd30d216d3404813
