### ISSUE TITLE
BiocCheckGitClone output

### ISSUE THREAD

**Issue by lshep** [Bioconductor/BiocCheck#156]
Opening an issue so you can give updates where we are at with this @LiNk-NY .  Without keeping track of details like BiocCheck users are confused by the BiocCheckGitClone output.  At the very least bad files for this check should be printed out rather than excluded.  We used to print out the files but now we don't and there have been several in the last week that inquire how to find these files.  It would be much easier for them to know exactly what file to remove like we used to.

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 

This was taken care of in d9aecdb694bafb7824fe9a6e221af6428d0999a4
You should see all the files now. 

Best,
Marcel
