### ISSUE TITLE
Clarifying objects initialized

### ISSUE THREAD

**Issue by llrs** [Bioconductor/BiocCheck#16]
There is an old issue Bioconductor/biocCheck.old#43 I found today.
It changed to a NOTE in the latest version:
```bash
* Checking to see if we understand object initialization....
    * NOTE: Consider clarifying how object ‘y’ (used in X) was
      initialized. Maybe it is part of a data set loaded with data(),
      or perhaps part of an object referenced in with() or within().
```

What is the meaning of this "Consider clarifying how object ‘y’ (used in X) was initialized"? How can it be clarified?

**Comment by mtmorgan** [comment]
@llrs indicated elsewhere that he'd post any followup to bioc-devel.
