### ISSUE TITLE
Tests failing with knitr 1.40

### ISSUE THREAD

**Issue by nileshpatra** [Bioconductor/BiocCheck#168]
Hi,

In bioccheck 1.32.0 (current bioconductor release) tests are failing with knitr 1.40 (both in debian package, and bioc release)
Command: `R --no-save < runTests.R`

Relevant log (hopefully):

```
Timing stopped at: 0 0 0
Error in DEACTIVATED("Skip this test, it requires a package non-available in Debian") : 
  Skip this test, it requires a package non-available in Debian
    * ERROR: No vignette sources in vignettes/ directory.
    * WARNING: Vignette(s) missing '\%VignetteIndexEntry{Vignette
      Title}'.
    * WARNING: Evaluate more vignette chunks.
        # of code chunks: 1
        # of eval=FALSE: 0
        # of nonexecutable code chunks by syntax: 1
        # total unevaluated 1 (100%)
    * NOTE: 'sessionInfo' not found in vignette(s)
Timing stopped at: 0.044 0.001 0.045
Error in checkTrue(identical(.BiocCheck$getNum(c("error", "warning", "note")),  : 
  Test not TRUE
expected 1 warning and 1 note


RUNIT TEST PROTOCOL -- Tue Aug 30 15:30:04 2022 
*********************************************** 
Number of test functions: 46 
Number of deactivated test functions: 3 
Number of errors: 0 
Number of failures: 1 
```

Full log - https://ci.debian.net/data/autopkgtest/testing/amd64/r/r-bioc-bioccheck/25509446/log.gz

I am having a hard time parsing the output properly and inspecting what went wrong, and hence would appreciate help.

**Comment by LiNk-NY** [comment]
Hi @nileshpatra 
This should be resolved in version `1.32.1` in Bioc 3.15. 
https://bioconductor.org/checkResults/release/bioc-LATEST/BiocCheck/
Re-open if you are still seeing an issue. 
Best,
Marcel
