### ISSUE TITLE
Warning in nzchar(fpath) && !is.na(fpath) 

### ISSUE THREAD

**Issue by Shians** [Bioconductor/BiocCheck#171]
I get this error when I use BiocCheck on my package NanoMethViz. As far as I can tell this is an error in BiocCheck code found in `getDirFile()`. As far as I can tell this warning can't happen because fpath should be guaranteed to be length 1, though I couldn't work out how to hook anything into the function to check because BiocCheck seems to do something funny with `print()` and `message()` calls.

**Comment by LiNk-NY** [comment]
Are you using a recent version of `BiocCheck`? 
This was resolved in https://github.com/Bioconductor/BiocCheck/pull/163 AFAICT
I can't reproduce on `NanoMethViz`.

**Comment by Shians** [comment]
I was using the BioC release version previously. The issue has been fixed in the Github version. Cheers.
