### ISSUE TITLE
`BiocCheck`: failing on bioconductor devel

### ISSUE THREAD

**Issue by bschilder** [Bioconductor/BiocCheck#174]
Just FYI, BiocCheck isn't available on Bioc 3.17 due to failing checks since 2 days ago:

http://bioconductor.org/checkResults/devel/bioc-LATEST/BiocCheck/

**Comment by LiNk-NY** [comment]
Hi Brian, @bschilder 
This should be resolved. 
Please @ me next time otherwise I may miss your issue. 
Best,
Marcel

**Comment by bschilder** [comment]
Will do. You might find these docs helpful too @LiNk-NY . 
https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/about-notifications#notifications-and-subscriptions

You may want to adjust you notification settings here:
<img width="392" alt="Screenshot 2022-12-16 at 14 51 08" src="https://user-images.githubusercontent.com/34280215/208178010-ed541973-8616-4ee1-919d-827a97858c6d.png">

**Comment by LiNk-NY** [comment]
Thanks. Yes, it is already set to `All Activity` but I did not get a notification via email or may have missed it.
