### ISSUE TITLE
False positive checking for value section in Rd files

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/BiocCheck#189]
Hi @LiNk-NY 

I think the recent changes for checking return sections in Rd files might be triggering a false positive.  Specifically I'm thinking of man pages that document the package itself, which I wouldn't expect to have a return section.

These are described in [r-pkgs.org](https://r-pkgs.org/man.html#sec-man-package-doc) and I have a specific example in [Rarr](https://github.com/grimbough/Rarr/blob/devel/man/Rarr.Rd) which is now triggering a warning in BiocCheck when it did not in the past.

If you agree it's a false positive, I wonder if you can use `BiocCheck:::docType(rd) == "package"` somewhere to test for this scenario.

Cheers,
Mike

**Comment by LiNk-NY** [comment]
Thanks for reporting. It should be resolved in ad4d1c88117d0ad808d12a6935b095de703cd859

**Comment by grimbough** [comment]
Awesome, thanks a lot!
