### ISSUE TITLE
What is codetoolsBioC ?

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/BiocCheck#191]
Hi Marcel @LiNk-NY ,

I just tried to install BiocCheck using pak, and it complained about not being able to find codetoolsBioC.  I think this is because pak tries to installed everything from the `DESCRIPTION` file, including `ENHANCES`, which BiocCheck has.

https://github.com/Bioconductor/BiocCheck/blob/6b242a9842a974150909dff5d8ab98640e01c94d/DESCRIPTION#L36

I just wondered if that was still relevant in the DESCRIPTION file.  AFAICS codetoolsBioC isn't in Bioconductor and the repo at https://github.com/Bioconductor/codetoolsBioC looks pretty stale.  I can get pak to skip trying to install it, so this is low priority, but maybe it doesn't need to be mentioned any more.

Cheers,
Mike

**Comment by LiNk-NY** [comment]
Hi Mike, @grimbough 

Thanks for bringing this up. It is best to defunct and archive the `codetoolsBioC` package.
Any functionality from `codetoolsBioC` that is absolutely necessary should go into `BiocPkgTools`.
I have removed the relevant code from `BiocCheck`.

Best,
Marcel
