### ISSUE TITLE
Error when checking for deprecated package usage

### ISSUE THREAD

**Issue by catavallejos** [Bioconductor/BiocCheck#194]
Hi all,

I am currently getting an error when running `BiocCheck`. The issue arises in the call to `BiocCheck:::getAllDeprecatedPkgs()`, particularly via `get_deprecated_status("release")`. Here is the error I got:

```
> BiocCheck:::get_deprecated_status("release")
Error in `[.data.frame`(pkg_status, , "PackageStatus") : 
  undefined columns selected
```

Any clues?

Many thanks in advance for your help.

Best
Cata

**Comment by LiNk-NY** [comment]
Hi Cata, @catavallejos 

What version of `BiocCheck` are you using? Do you have the latest?
If not, try with the latest version and post the `sessionInfo` here. 

Best,
Marcel

**Comment by catavallejos** [comment]
Hi Marcel,

I am using 1.36.0, which is the latest version in Bioc Release.

Best
Cata

**Comment by catavallejos** [comment]
Hi @LiNk-NY 

I installed the latest version from Github and I get the same error:

```
> BiocCheck()
─ BiocCheckVersion: 1.37.2
─ BiocVersion: 3.17
─ Package: BASiCS
─ PackageVersion: 2.13.4
─ sourceDir: /Users/catavallejos/Documents/GitHub/BASiCS
─ installDir: /var/folders/87/27s64xsn2qq4tc1qgkfzq8qm0000gq/T//Rtmp0OZn3E/file950ff25a663
─ BiocCheckDir: /Users/catavallejos/Documents/GitHub/BASiCS.BiocCheck
─ platform: unix
─ isTarBall: FALSE

* Installing package...
* Checking for deprecated package usage...
Error in `[.data.frame`(pkg_status, , "PackageStatus") : 
  undefined columns selected
```

**Comment by LiNk-NY** [comment]
It looks like there is a CloudFront issue with the file that is accessed. I've applied a more robust way of querying the file. Version `1.36.1` of `BiocCheck` should be available on Bioconductor release within 48 hours.

**Comment by catavallejos** [comment]
Thanks for resolving this so quickly @LiNk-NY !

**Comment by LiNk-NY** [comment]
FWIW You can install the future release version of the package with 
```r
BiocManager::install("Bioconductor/BiocCheck", ref = "RELEASE_3_17")
```
