### ISSUE TITLE
BiocCheck should not be a Bioc-mirror fork

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocCheck#20]
There should be no forks coming out of Bioconductor-mirror.
The mirror is deprecated.

Please update the `BiocCheck` repository in the git server if there are any differences
and use the git server repository version to create a new repository under
the Bioconductor account.

Thanks!

Regards,
Marcel

**Comment by mtmorgan** [comment]
it's true that the repository forked from the mirror, but that is a historical tag. I could remove this repository and start a new one, with identical content, but then I'd loose the issues and other github activities, and I wouldn't be able to close this issue!

**Comment by LiNk-NY** [comment]
I agree but when we recommend against using the Bioconductor-mirror, we should follow our own recommendations :smile:
