### ISSUE TITLE
Addressing "Checking if other packages can import this one" errors when packages providing functions are imported in NAMESPACE

### ISSUE THREAD

**Issue by jmitchell81** [Bioconductor/BiocCheck#200]
Hello. I am having trouble interpreting an error from BiocCheck during the check "Checking if other packages can import this one...". There are multiple objects provided from other packages that the error says are not imported in the NAMESPACE when these packages are included. One of errors says the 'methods::new' function is not imported when I have not used 'new' within the function definition the log says this occurs within.

Here is the error message from the log

```
* Checking if other packages can import this one...
* ERROR: Packages providing 7 object(s) used in this package should be imported in the NAMESPACE file, otherwise packages importing this package may fail.
package::object in function()
utils::read.csv in create_domino()
stats::wilcox.test in create_domino()
stats::sd in create_domino ()
stats::cor.test in create_domino()
methods::new in domino()
grDevices::hcl in ggplot_col_gen()
igraph::clusters in rename_clusters()
```

Focusing on the "methods::new in domino()". methods is included in "Imports:" in my DESCRIPTION file and in my NAMESPACE as 

```
import(methods)
```

and the definition of the domino class has no usage of methods::new

```
domino <- methods::setClass(
  Class = "domino",
  slots = c(
    db_info="list",
    z_scores="matrix",
    counts="dgCMatrix",
    clusters="factor",
    features="matrix",
    cor="matrix",
    linkages="list",
    clust_de="matrix",
    misc="list",
    cl_signaling_matrices="list",
    signaling="matrix"
  )
)
```

I have used functions from the methods package elsewhere in my scripts in R/ that are not generating these errors. As I am trying to address these errors, are there other places in my package directory that I should be looking to correct these errors besides NAMESPACE and DESCRIPTION?

**Comment by jmitchell81** [comment]
I was able to resolve this issue when correcting another check. My project directory name did not match the name of the package. Upon changing the directory's name to match the package, I received no errors from "Checking if other packages can import this one...".

**Comment by LiNk-NY** [comment]
Hi @jmitchell81 

What version of `BiocCheck` are you using? Make sure you have the most up-to-date version. Also, note that `domino()` internal function makes a call to `new()`. 

Best, 
Marcel
