### ISSUE TITLE
Stringent doi checking of CITATION in ` BiocCheckGitClone`

### ISSUE THREAD

**Issue by boyiguo1** [Bioconductor/BiocCheck#208]
The lack of or empty doi field in CITATION file seems to tiger a warning message during `BiocCheckGitClone`.
> * Checking that provided CITATION file is correctly formatted...
       WARNING: Include the 'doi' argument in CITATION 'bibentry()'

see example report `https://bioconductor.org/spb_reports/tpSVG_buildreport_20240112133848.html`

Compared to packages that doesn't have a CITATION file at all, `BiocCheckGitClone` seems only returns a `NOTE`
> * Checking CITATION...
    * NOTE: No CITATION file found. Bioconductor packages are not
      required to have a CITATION file but it is useful both for users
      and for tracking Bioconductor project-wide metrics. If you later
      post a preprint or publish a paper about your Bioconductor
      package, please add the details with a 'doi' argument in the
      CITATION file's 'bibentry()'.

I think this design is counter-intuitive, especially during bioc package submission when bioc doi is unknown.

I would like to politely ask the maintainer to consider to relax the check of `doi`in existing CITATION file, changing from a `WARNING` to `NOTE`.

Thank you very much.

**Comment by LiNk-NY** [comment]
Hi @boyiguo1 
It is a warning because CITATION files are usually for articles e.g., `citation("GenomicRanges")`.
If you don't have a publication, it may be better to go with the stock `citation()` output rather than to have a `CITATION` file.

Compare without a `CITATION` file: 

```r
> citation(package = "tpSVG")
To cite package 'tpSVG' in publications use:

  Guo B, Hicks S (????). _tpSVG: Thin plate models to detect spatially variable genes_. R package version 0.99.3,
  <https://github.com/boyiguo1/tpSVG>.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {tpSVG: Thin plate models to detect spatially variable genes},
    author = {Boyi Guo and Stephanie C. Hicks},
    note = {R package version 0.99.3},
    url = {https://github.com/boyiguo1/tpSVG},
  }
Warning message:
In citation(package = "tpSVG") :
  could not determine year for 'tpSVG' from package DESCRIPTION file
```

versus with the included `CITATION` file:

```r
> citation(package = "tpSVG")
To cite escheR in publications use:

  Guo B, Weber LM, Hicks SC (2023). "tpSVG." R package version 0.99.1. https://boyi-guo.com/tpSVG/.

A BibTeX entry for LaTeX users is

  @Misc{,
    title = {tpSVG},
    author = {Boyi Guo and Lukas M. Weber and Stephanie C. Hicks},
    note = {R package version 0.99.1. https://boyi-guo.com/tpSVG/},
    year = {2023},
    month = {12},
  }
```

You would also avoid errors like `escheR` and stale versions (`0.99.1`) in the CITATION file :)
