### ISSUE TITLE
Misleading error message for documentation check

### ISSUE THREAD

**Issue by assaron** [Bioconductor/BiocCheck#21]
One of the error messages that BiocCheck can spit out is: "At least 80% of man pages documenting exported objects must have runnable examples".

However, the actual assert is that _more_ than 80% of exported objects should be covered: https://github.com/Bioconductor/BiocCheck/blob/master/R/checks.R#L950

Additionally, I would suggest to change this check when there are small number of functions exported (<= 5), otherwise it means that all the functions should have runnable examples which could be impractical for some cases.

**Comment by LiNk-NY** [comment]
I agree with this, especially for experiment data packages.

**Comment by lshep** [comment]
This is resolved in BiocCheck_1.15.3.  The check has been updated to be for 80% or more.  

After speaking with the team we still feel like special allowances for small number of exported functions should not be allowed.  If there are only a small number of functions than we feel it is even more imperative to accurately display usage through runnable examples;  experiment data packages runnable example at minimum should be to load the data.
