### ISSUE TITLE
Possible bug in .getTokenTextCode

### ISSUE THREAD

**Issue by llrs** [Bioconductor/BiocCheck#214]
A package maintainer [is facing a problem](https://github.com/Bioconductor/Contributions/issues/3452#issuecomment-2247570173) in the submission of the package to Bioconductor. I think this is due to a bug in BiocCheck.

There is a check if there is any condition met but then it is assumed there is only one (`seq(...)`)

https://github.com/Bioconductor/BiocCheck/blob/222e4693a947673ef16d9e6982e7f1c14e2c705f/R/findSymbols.R#L11-L12

`cond` is defined above as a vector, so multiple conditions can happen:
https://github.com/Bioconductor/BiocCheck/blob/222e4693a947673ef16d9e6982e7f1c14e2c705f/R/findSymbols.R#L4

I don't understand fully the problem so I am not sure what is the best solution to fix this.

**Comment by LiNk-NY** [comment]
This has been resolved in the latest version of `BiocCheck`: 48130c9  v1.41.9
Best,
Marcel
