### ISSUE TITLE
Fails to print deprecated package names

### ISSUE THREAD

**Issue by ChangqingW** [Bioconductor/BiocCheck#217]
When I ran `BiocCheck::BiocCheck` in the console, it finds deprecated packages but fails to print out their names, leaving a very confusing message like the following:
```
> BiocCheck::BiocCheck('~/FLAMES')
─ BiocCheckVersion: 1.40.0
─ BiocVersion: 3.19
─ Package: FLAMES
─ PackageVersion: 1.11.0
─ sourceDir: /home/q/FLAMES
─ installDir: /tmp/Rtmp2K0NzR/fileb70dc7d74255d
─ BiocCheckDir: /home/q/FLAMES.BiocCheck
─ platform: unix
─ isTarBall: FALSE

* Installing package...
* Checking for deprecated package usage...
    * ERROR: Package dependency in the DESCRIPTION is 'Deprecated'.
      Update your package to not rely on the following:
* Checking for remote package usage...
* Checking for 'LazyData: true' usage...
```

```
> sessionInfo()

R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.12.0
LAPACK: /usr/lib/liblapack.so.3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Australia/Melbourne
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] BiocCheck_1.40.0 roxygen2_7.3.2
```
This also happens to [our Github Action](https://github.com/mritchielab/FLAMES/blob/devel/.github/workflows/check-bioc.yml) set up by `biocthis::use_github_action`

**Comment by ChangqingW** [comment]
I got the package name from `debug(BiocCheck:::checkDeprecatedPackages)`, but not sure why this is not printed to the console
```
Browse[1]> allDeprecated[logVec]
[1] "zlibbioc"
```

**Comment by lshep** [comment]
There is a directory similar to when running R CMD  check that normally is  `nameOfPackage.BiocCheck`.  Normally in this directory there is a more detail explanations of notes/warnings/errors

**Comment by LiNk-NY** [comment]
@ChangqingW 

Note that you should be using Bioc-devel and consequently, the devel 
version of `BiocCheck`, especially if you're developing a package. 
I have updated `BiocCheck` to include the first 3 lines of errant 
code. See version `1.41.13`. 

Best,
Marcel
