### ISSUE TITLE
BiocCheck is not compatible with 'Authors@R' in DESCRIPTION

### ISSUE THREAD

**Issue by zhengxwen** [Bioconductor/BiocCheck#28]
Fields ‘Author’ and ‘Maintainer’ are auto-generated from ‘Authors@R’, but R indents the lines with 2 spaces instead of 4.

**Comment by dtenenba** [comment]
Please supply an example, link to a package that causes this. Also, it doesn't sound from your description like this is actually a problem; if the lines are indented 2 spaces, is that not still a valid DESCRIPTION file?

**Comment by zhengxwen** [comment]
There is nothing wrong with R and BiocCheck themselves. For example, I have a package [foo (https://dl.dropboxusercontent.com/u/51499461/tmp/foo_1.0.0.tar.gz)](https://dl.dropboxusercontent.com/u/51499461/tmp/foo_1.0.0.tar.gz)

The original DESCRIPTION in my folder is (no fields ‘Author’ and ‘Maintainer’):
```
Package: foo
Type: Package
Title: What the package does (short line)
Version: 1.0.0
Date: 2015-01-01
Authors@R: c(person("Xiuwen", "Zheng", role=c("aut", "cre"),
        email="zhengx@u.washington.edu"),
        person("Stephanie", "Gogarten", role="ctb"),
        person("Cathy", "Laurie", role="ctb"))
Description: More about what it does (maybe more than one line)
License: GPL-3
biocViews: Software
```

After I run `R CMD build foo`, the fields ‘Author’ and ‘Maintainer’ are auto-generated from ‘Authors@R’ and appended to DESCRIPTION in "foo_1.0.0.tar.gz". The lines are indented 2 spaces:
```
Package: foo
Type: Package
Title: What the package does (short line)
Version: 1.0.0
Date: 2015-01-01
Authors@R: c(person("Xiuwen", "Zheng", role=c("aut", "cre"),
        email="zhengx@u.washington.edu"),
        person("Stephanie", "Gogarten", role="ctb"),
        person("Cathy", "Laurie", role="ctb"))
Description: More about what it does (maybe more than one line)
License: GPL-3
biocViews: Software
Packaged: 2015-01-02 09:03:17 UTC; sts
Author: Xiuwen Zheng [aut, cre],
  Stephanie Gogarten [ctb],
  Cathy Laurie [ctb]
Maintainer: Xiuwen Zheng <zhengx@u.washington.edu>
```

`R CMD BiocCheck foo_1.0.0.tar.gz` reports
```
* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * CONSIDER: Indenting lines with a multiple of 4 spaces; 2 lines
      (1%) are not.
```
Since the current BiocCheck does not report which file has this CONSIDER problem, it seems difficult to identify the problem of indenting lines in the new 'DESCRIPTION' file.
