### ISSUE TITLE
Failed BiocCheck when using knitr Engine in rnw vignette

### ISSUE THREAD

**Issue by c-mertes** [Bioconductor/BiocCheck#31]
I encountered problems with the new BiocCheck version in the devel branch.

In the release version it is running through with no problems. in the devel version it stops with the following error:

```
Error in match.arg(options$results, c("verbatim", "tex", "hide")) : 
  'arg' should be one of “verbatim”, “tex”, “hide”
Calls: <Anonymous> ... Stangle -> Sweave -> SweaveParseOptions -> check -> match.arg
Execution halted
```
For more details I have our package on travis, where the error message can be checked. 
https://travis-ci.org/gagneurlab/OUTRIDER/builds/397133569 

I tracked it down to the function call 
`BiocCheck -> checkCodingPractice -> checkLogicalUseFiles -> makeTempRFile`

I think the problem is, that the function assumes it is in Sweave format, if the ending is rnw, but ignores the vignette engine. We use the knitr engine and therefore it cant be parsed by Stangle. I guess adding an check for the vignette engine should do the trick. 

I will add do a PR for this issue.

If I used the file ending in conjunction with the vignette engine in a wrong way, please let me know.

**Comment by c-mertes** [comment]
This change solved my problem locally.

**Comment by lshep** [comment]
do you have a github link to your package that I might test it out more thoroughly?   Also did you specify the VignetteEngine and VignetteBuilder in the DESCRIPTION and the vignette?

**Comment by c-mertes** [comment]
This is our github package: https://github.com/gagneurlab/OUTRIDER
I have both set:
[DESCRIPTION-file: VignetteBuilder: knitr](https://github.com/gagneurlab/OUTRIDER/blob/master/DESCRIPTION#L26)
[Vignette-file: %\VignetteEngine{knitr::knitr}](https://github.com/gagneurlab/OUTRIDER/blob/master/vignettes/OUTRIDER.Rnw#L3)

**Comment by lshep** [comment]
Thank you; we appreciate you reporting this.  I'll look into this and your pull request.

**Comment by lshep** [comment]
Thank you!

**Comment by c-mertes** [comment]
I realised just now by reading the BiocStyle vignette that the regex can match multiple times. And the last commit will let BiocStyle fail.

We are interested only in the first occurrence of the VignetteEngine. I found the `vigHelper` function, which makes the code cleaner and there we can check only against the first occurrence of it.

Hope this solves the problem.

**Comment by lshep** [comment]
This is actually a very specific case because BiocStyle describes how to set up the vignette header information -   part of BiocCheck is that only one VignetteEngine is specified in the vignette and will have an ERROR if it is.  But it does make the check better so thank you for your diligence.
