### ISSUE TITLE
BiocCheck exit code

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocCheck#34]
Hi Martin and Lori, @mtmorgan @lshep 

I've integrated Travis-CI with `BiocCheck` but I'm still having issues getting an non-zero exit code
when running `BiocCheck` via `Rscript`:

```
git clone git@github.com:waldronlab/MultiAssayExperiment && cd MultiAssayExperiment
Rscript -e "BiocCheck::BiocCheck()"
```
the return code is 
```
$ echo $?
0
```
when it should be a `1`. 

The exit code works okay via `R CMD BiocCheck`. 

Regards,
Marcel

**Comment by mtmorgan** [comment]
in the spirit of it all, can you make a better reproducible example, i.e., one that runs quickly and is guaranteed to always show the problematic behavior?

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 
I took a few minutes to create a better reproducible example. 
I created a dummy package where this issue is isolated for the most part.
It runs much faster. 

```
git clone git@github.com:LiNk-NY/TestPkg.git && cd TestPkg
Rscript -e "BiocCheck::BiocCheck()"
```

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Travis build result is here https://travis-ci.org/LiNk-NY/TestPkg/builds/399663256

**Comment by lshep** [comment]
@mtmorgan I'm wondering if it has to do with BiocCheck when run from command line quits with status code but  otherwise returns the list of detailed messages https://github.com/Bioconductor/BiocCheck/blob/master/R/BiocCheck.R#L236   

@LiNk-NY do we care about warnings? are they considered passing? Does travis pick up on a different code for warnings that we should be outputting as well?

**Comment by LiNk-NY** [comment]
@lshep Warnings can be converted to errors in the `.travis.yml` file with the `warnings_are_errors: true` option. I'm not sure how that mechanism works though.

**Comment by mtmorgan** [comment]
this is what BiocCheck itself does
```
> noquote(readLines(R.home("bin/BiocCheck")))
[1] #!/bin/sh                                                               
[2]                                                                         
[3] R_SCRIPT="suppressPackageStartupMessages(library(methods))"             
[4] R_SCRIPT="$R_SCRIPT; suppressPackageStartupMessages(library(BiocCheck))"
[5] R_SCRIPT="$R_SCRIPT; BiocCheck:::.BiocCheckFromCommandLine()"           
[6]                                                                         
[7] echo "$R_SCRIPT" | $R_HOME/bin/R --vanilla --slave --args $*            
[8]   
```
and
```
bioc-dev -e "BiocCheck:::.BiocCheckFromCommandLine()" --args "."
```
returns an error return code; I don't think we want to change the interactive behavior

**Comment by LiNk-NY** [comment]
@mtmorgan 
`noquote(readLines(R.home("bin/BiocCheck")))`
Wouldn't this be equivalent to `bioc-dev CMD BiocCheck .` ? 

It seems to me that the `Rscript` call is not being interpreted as a command line call? 
Therefore I should use something like:

```
bioc-dev -e "BiocCheck::BiocCheck(Called_from_command_line = TRUE)"
```
Looks a bit clunky but it works.

**Comment by lshep** [comment]
So have we decided the behavior shoudn't be changed and this issue can be closed?   Should I (do you think it would be helpful to)  make any documentation about this in the vignette?

**Comment by mtmorgan** [comment]
It seems like Rscript things that it is not running interactively, and so BiocCheck should I think exit accordingly -- 
```
TestPkg master$ Rscript --vanilla -e "interactive()"
[1] FALSE
```
probably by augmentig the final `if(interactive() || ...)` in `BiocCheck()`.

**Comment by LiNk-NY** [comment]
Okay, I can make this change and send a PR. Thanks Martin @mtmorgan

**Comment by LiNk-NY** [comment]
@lshep I don't think we need to document this behavior as the recommended way of using `BiocCheck` is via the command line `R CMD BiocCheck .`.
I will add a tidbit about `BiocCheck` being supported via Travis-CI.

**Comment by lshep** [comment]
Thanks
