### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by llrs** [Bioconductor/BiocCheck#36]
See this [submission](https://github.com/Bioconductor/Contributions/issues/900#issuecomment-427732605) where the issue was raised.

This is related  to this helper file, which unexpectedly returns more than one element (perhaps this should be separate function?):
https://github.com/Bioconductor/BiocCheck/blob/6fa591de155281b071e47042369688b3b62c8f6c/R/checks.R#L227-L236

It could be solved via by changing `return(...)` to `return(all(eng %in% builder))`

**Comment by lshep** [comment]
Thank you for reporting this -  I will look into adding a check that the vignetteEngine is only specified once and into the suggested all()  addition because as you pointed out having more than one Engine specified is also a mistake.
