### ISSUE TITLE
.git etc not ignored by checkIndivFileSizes

### ISSUE THREAD

**Issue by JoFAM** [Bioconductor/BiocCheck#39]
When running BiocCheck() on the RCM package ( https://github.com/CenterForStatistics-UGent/RCM ) I get the following warning : 

```
$warning
[1] "The following files are over 5MB in size: '.git/objects/pack/pack-740ada64c24e3f429d86431cae7e341dab19b815.pack'"
```

That's pretty odd, as the .git folder is a hidden folder in the root directory and part of the git system. I have added the following to .Rbuildignore : 

```
\.gitignore
\.git/*
```
but to no avail. I keep getting the same warning, which doesn't even make sense. Warning is given every time when I try to run `BiocCheck::BiocCheck()` from the console in the RStudio project for this package.

**EDIT**:

Traced the problem back to `checkIndivFileSizes` which just takes all files and folders of the project directory (as opposed to the installed package). That's why I also changed the title of the issue. 

For reference: I first thought it was an issue with R CMD INSTALL and contacted r-devel for this:

https://stat.ethz.ch/pipermail/r-devel/2018-December/077091.html

**Comment by JoFAM** [comment]
Did some further diggin, and this can be traced back to the function `installAndLoad`. This one uses R CMD INSTALL which doesn't take .Rbuildignore into account if I remember right. It looks like R CMD INSTALL also doesn't ignore .git folders.

**Comment by lshep** [comment]
The .git directory should not be ignored.  Git history remembers large objects even after they are removed.  There have been some similar posts that @nturaga has answered.  Please see the following references

https://stat.ethz.ch/pipermail/bioc-devel/2019-February/014703.html

Within that post he references the following pages as well:
http://bioconductor.org/developers/how-to/git/remove-large-data/
https://stat.ethz.ch/pipermail/bioc-devel/2018-November/014274.html
