### ISSUE TITLE
BiocCheck breaks when `[` is aliased.

### ISSUE THREAD

**Issue by Shians** [Bioconductor/BiocCheck#41]
If you put

```r
foo <- `[`
```

Somewhere in a package, it will trigger

```r
Error in makeUsageCollector(fun, ...) : only works for closures
```

In BiocCheck::BiocCheck() (version 1.18.0). This comes from

```r
if (typeof(fun) != "closure")
       stop("only works for closures")
```

In codetools::makeUsageCollector(), and the fact that

```r
typeof(\`[\`)
## "special"
```

**Comment by mtmorgan** [comment]
Further discussion on the bioc-devel mailing list... https://stat.ethz.ch/pipermail/bioc-devel/2018-December/014451.html
