### ISSUE TITLE
Dependency on R version

### ISSUE THREAD

**Issue by llrs** [Bioconductor/BiocCheck#42]
The BioCheck gives a warning when R version is below the intended R version used for the release. But per Martin's comment it seems that the dependency on R or a specific R version can be omitted.

The relevant messages are on this thread:
https://stat.ethz.ch/pipermail/bioc-devel/2019-January/014555.html

**Comment by lshep** [comment]
I don't think the R check should be removed,  It is our strong suggestion to include the version the builder tests on as we cannot determine if any other dependencies have changed in previous versions and can ensure a working copy - it is already a WARNING the only suggestion I would have would be to change to a NOTE but I think this check is fine as is as a WARNING ... @mtmorgan   input?

**Comment by mtmorgan** [comment]
Agree with Lori, see further discussion in the email thread.
