### ISSUE TITLE
Incomplete error information

### ISSUE THREAD

**Issue by Jiefei-Wang** [Bioconductor/BiocCheck#43]
If the biocViews field is empty in the DESCRIPTION file, the error message would be:
```
$`error`
[1] "Add biocViews other than "
```
which is hard to understand, It might be better if the error message can be more informative in this case.

**Comment by lshep** [comment]
It gives and informative error if the biocViews is missing completely from the Description 

If you read the documentation to add the field to the description to begin with, why wouldn't you follow the advice to add a term?

**Comment by Jiefei-Wang** [comment]
I know this is not a bug, Just a minor comment, the message could be more instructive by saying something like(Which is the error message when there is no biocViews in the DESCRIPTION file):
```
$`error`
[1] "No biocViews terms found"
```

I haven't decided which term I should put in this field so I left the field empty. This might be uncommon but just for the next person who did the same mistake as me...

**Comment by lshep** [comment]
Valid point. I'll look at catching that edge case.

Lori Shepherd
Bioconductor Core Team
Roswell Park Cancer Institute
Department of Biostatistics & Bioinformatics
Elm & Carlton Streets
Buffalo, New York 14263
________________________________
