### ISSUE TITLE
Add test for Remotes?

### ISSUE THREAD

**Issue by smped** [Bioconductor/BiocCheck#44]
This one just tripped me up, so I wonder if it's worth adding a test to BiocCheck that checks for packages listed in the Remotes field in the DESCRIPTION file. I'm not totally up with the structure of the BiocCheck package so my apologies if this is clumsy, but maybe something along the lines of:

```
checkRemotes <- function(pkgdir)
{
    ## Parse the DESCRIPTION FILE
    dcf <- read.dcf(file.path(pkgdir, "DESCRIPTION"))
    ## Check for the presence of anything in the Remotes field
    chkRemotes <- grepl("Remotes", colnames(dcf))
    
    if (any(chkRemotes)){
        handleError("Package dependency in the DESCRIPTION is not hosted on",
                    "CRAN or Bioconductor")
    }
}
```

**Comment by lshep** [comment]
Thank you for pointing this out; we will consider your proposal.

**Comment by lshep** [comment]
Out of curiosity where you getting an ERROR somewhere when you had the remotes field in the DESCRIPTION?

**Comment by smped** [comment]
The build report is here and that was the first ERROR I saw.  https://bioconductor.org/spb_reports/ngsReports_buildreport_20190202043535.html

It passed local runs using R CMD check & BiocCheck using R 3.5.2. I was relying on travis for bioc-devel & also tested it using the available bioc-devel docker, with nothing being flagged.

The DESCRIPTION at the time of initial submission is visible here too if that helps https://github.com/Bioconductor/Contributions/issues/985

**Comment by lshep** [comment]
Thank you!
