### ISSUE TITLE
copy files in src folder with a filter

### ISSUE THREAD

**Issue by Jiefei-Wang** [Bioconductor/BiocCheck#49]
Hi,

I was using a 64 bit Windows system and trying to run `BiocCheck()` to test my package, the problem I have encountered is that `BiocCheck()` cannot work with `devtools::load_all()` function since it will make a compilation of the 32-bit package failed. The reason is that  `BiocCheck()` will create a `src-i386` folder which contains the same files as `src` folder and compile a 32bit dynamic library in that folder.  Because `load_all()` will compile code and leave compiled files in the `src` folder, a direct copy of `src` folder will also copy the compiled files. Therefore, `make ` will believe that the code has been compiled and try to link 64bit .o files to create a 32bit DLL and trigger an error. Here is the error message:

```
BiocCheck::BiocCheck()
This is BiocCheck version 1.19.31. BiocCheck is a work in progress. Output and severity of issues may
change. Installing package...
  cmd: C:/PROGRA~1/R/R-36~1.0/bin/R
  args: --vanilla CMD INSTALL --no-test-load --library=C:\Users\Jeff\AppData\Local\Temp\Rtmp6DcBjL\file1e2072347a9f/lib "C:/Users/Jeff/OneDrive/course material/work/Roswell park/SharedObject"
  stderr:
  * installing *source* package 'SharedObject' ...
  ** using staged installation
  ** libs
  
  *** arch - i386
  C:\Rtools\mingw_32\bin\nm.exe: C_interface.o: File format not recognized
  C:\Rtools\mingw_32\bin\nm.exe: C_memoryManagerInterface.o: File format not recognized
  C:\Rtools\mingw_32\bin\nm.exe: RcppExports.o: File format not recognized
  C:\Rtools\mingw_32\bin\nm.exe: altrepCommonFunc.o: File format not recognized
  C:\Rtools\mingw_32\bin\nm.exe: altrepRegistration.o: File format not recognized
  C:\Rtools\mingw_32\bin\nm.exe: memoryManager.o: File format not recognized
  C:\Rtools\mingw_32\bin\nm.exe: tools.o: File format not recognized
  C_interface.o: file not recognized: File format not recognized
  collect2.exe: error: ld returned 1 exit status
  no DLL was created
  ERROR: compilation failed for package 'SharedObject'
  * removing 'C:/Users/Jeff/AppData/Local/Temp/Rtmp6DcBjL/file1e2072347a9f/lib/SharedObject'
    * ERROR: C:/Users/Jeff/OneDrive/course material/work/Roswell park/SharedObject must be installable.
Error in (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  : 
  there is no package called ‘SharedObject’
```
After deleting all compiled files in the `src` folder, `BiocCheck()` works as usual. A solution for this problem can be using a filter when doing the copy of the `src` folder and filter out .o, .so, .dll files. I'm not sure if `BiocCheck()` has a control over it. If not, I would appreciate if you can direct me to the right place to submit this bug report.

Best,
Jiefei

**Comment by lshep** [comment]
I don't necessarily consider this a problem with BiocCheck.  devtools::load_all is meant as a development tool.  Compatibility with this function isn't necessarily a concern for BiocCheck.    R CMD check and R CMD BiocCheck are really meant to be run independently on package tar balls or package directories.  When submitting a package, compiled code should not be included and often causes problems (hence why we check for .o, .so, and .dll files and it should throw and ERROR and be removed from the package).   See https://github.com/Bioconductor/BiocCheck/blob/7829e31c46f8417163ab3727593eb083c002dabc/R/checks.R#L1523

Note this check is run when submitting a package but is run on the git clone to search for these pre-compiled and hidden files. It is call BiocCheckGitClone as is also documented.
