### ISSUE TITLE
Rcpp packages still triggering registered routine check.

### ISSUE THREAD

**Issue by jimhester** [Bioconductor/BiocCheck#5]
Dan made a commit to attempt to disable this check for packages using Rcpp [BiocCheck@ef3fff5fbb](https://github.com/Bioconductor/BiocCheck/commit/ef3fff5fbb1c518bac529985823336a3fd9a12fe) But this ends up not working because most Rcpp using packages use `Rcpp::compileAttributes()` and this generates a RcppExports.R file which contains `.Call()`. So in practice Rcpp packages still get this check and the subsequent RECOMMEND even when it is not completely applicable.

**Comment by vobencha** [comment]
I second demoting this check to CONSIDER in BiocCheck.

**Comment by lshep** [comment]
I think this is resolved
