### ISSUE TITLE
Misterious error "* Checking library calls... Error in parse(outfile, keep.source = TRUE) (...) unexpected symbol 6:  7: Create a"

### ISSUE THREAD

**Issue by lubianat** [Bioconductor/BiocCheck#51]
Hello,
I was running BiocCheck in a in-development package( www.github.com/lubianat/PubScore) and
I got an error in my BiocCheck that I was not able to figure out the source. 

This was the error found:

* Checking library calls...
Error in parse(outfile, keep.source = TRUE) : 
  /tmp/RtmpwYXYVW/file2cda59db730a/parseFile.tmp:7:8: unexpected symbol
6: 
7: Create a
          ^
When searching the internet, I could not find the solution for it.  

Do you know what might be causing that? Is that a common error? 

Thank you very much,
Tiago

**Comment by mtmorgan** [comment]
At this line https://github.com/lubianat/PubScore/blob/9ce25c1952742224b1c90c6d7698ed72841471f4/R/pubscore.R#L67 you intend to write a comment in an example, but instead you write a plain text. It should be

```
#' ## Create a ...
```
This is not an issue with BiocCheck; instead it is a problem with Bioconductor package development. In the future please ask on the [bioc-devel mailing list][1].

[1]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
