### ISSUE TITLE
Naughty behavior: installing files into R_HOME installation without asking for permission

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/BiocCheck#52]
Hi, I just discovered that the BiocCheck package installs files into `R.home("bin")` if [it can](https://github.com/Bioconductor/BiocCheck/blob/6722da6a506c38dccde96f6acff7f8a0e057aaa9/R/install.R#L1-L58):
```r
$ ls -l lib/R/bin/Bioc*
-rwxr-xr-x 1 hb hb 269 Aug 11 16:34 lib/R/bin/BiocCheck
-rwxr-xr-x 1 hb hb 277 Aug 11 16:34 lib/R/bin/BiocCheckGitClone
```
and it does so without asking for permission or notifying the user. It "just" happens when the package is loaded:

https://github.com/Bioconductor/BiocCheck/blob/6722da6a506c38dccde96f6acff7f8a0e057aaa9/R/zzz.R#L20-L25

It also happens when the package is installed.

# Example

```
$ Rscript -e 'dir(R.home("bin"), pattern="Bioc")'
character(0)
$ Rscript -e 'BiocManager::install("BiocCheck")'
[...]
BiocCheck and BiocCheckGitClone script installed.
[...]
$ Rscript -e 'dir(R.home("bin"), pattern="Bioc")'
[1] "BiocCheck"         "BiocCheckGitClone"

$ Rscript -e 'file.remove(dir(R.home("bin"), pattern="Bioc", full.names=TRUE))'
[1] TRUE TRUE

$ Rscript -e 'loadNamespace("BiocCheck")'
BiocCheck and BiocCheckGitClone script installed.
<environment: namespace:BiocCheck>

$ Rscript -e 'dir(R.home("bin"), pattern="Bioc")'
[1] "BiocCheck"         "BiocCheckGitClone"
```

I argue that this is rather bad behavior.  This hack sets a precedence that it's ok to do so. At a minimum, it should always ask the user for permission prior to installing files, especially to `R.home()`.

On a related note: I do find it useful we could have customized flavors of `R CMD check`, just like `--as-cran` is one.  Something like:
```
R CMD check --flavor=CRAN MyPkg
R CMD check --flavor=Bioconductor MyPkg
```
I think this is something we could convince R core to implement.  I've started a discussion on this at https://github.com/HenrikBengtsson/Wishlist-for-R/issues/16 a while back.

**Comment by lshep** [comment]
We have decided to remove the command line option for running BiocCheck and BiocCheckGitClone. BiocCheck and BiocCheckGitClone command line will be deprecated in 3.12 and removed in 3.13. This should allow the writing and self-install portions to be removed. The documentation and recommended running will be from within R.

**Comment by HenrikBengtsson** [comment]
Thanks for revamping this.

**Comment by lshep** [comment]
We won't officially remove all the naughty behavior until after the 3.13 release at the end of October and keep it deprecated message in 3.12.  Cheers

**Comment by HenrikBengtsson** [comment]
:+1: Totally understand. Deprecating things takes a long time.
