### ISSUE TITLE
Check failure on R Markdown templates containing child chunks

### ISSUE THREAD

**Issue by mjsteinbaugh** [Bioconductor/BiocCheck#54]
Hi, I'm running into an issue with BiocCheck failing on R Markdown templates that contain chunks with a child call to an external file. For example, the templates in [bcbioRNASeq](https://bioinformatics.sph.harvard.edu/bcbioRNASeq/) work fine but are causing BiocCheck to error.

Here's an example:
https://github.com/hbc/bcbioRNASeq/blob/master/inst/rmarkdown/templates/quality-control/skeleton/skeleton.Rmd

BiocCheck is returning an error because `_header.Rmd` doesn't exist in the same directory as the source R Markdown in the package. That's true, but the file is downloaded by the `prepareTemplate()` function defined in [basejump](https://basejump.acidgenomics.com/); see [`prepareTemplate()`](https://github.com/acidgenomics/basejump/blob/master/R/prepareTemplate.R) source code. This makes juggling shared header, footer, and setup files a lot easier across templates and packages.

Here's an example output of the check failure:

```
* Checking coding practice...
Warning in file(con, "r") :
  cannot open file '/data00/bcbioRNASeq/inst/rmarkdown/templates/differential-expression/skeleton/_header.Rmd': No such file or directory
Calls: BiocCheck ... process_tangle.block -> lapply -> FUN -> knit -> readLines -> file
Quitting from lines 45-45 (/data00/bcbioRNASeq/inst/rmarkdown/templates/differential-expression/skeleton/_header.Rmd)
Error in file(con, "r") : cannot open the connection
Calls: BiocCheck ... process_tangle.block -> lapply -> FUN -> knit -> readLines -> file
Backtrace:
     █
  1. └─global::BiocCheck()
  2.   └─BiocCheck::BiocCheck(...)
  3.     └─BiocCheck:::checkCodingPractice(package_dir, parsedCode, package_name)
  4.       └─BiocCheck:::checkLogicalUseFiles(pkgdir)
  5.         ├─base::unlist(lapply(FUN = makeTempRFile, allFiles))
  6.         └─base::lapply(FUN = makeTempRFile, allFiles)
  7.           └─BiocCheck:::FUN(X[[i]], ...)
  8.             └─knitr::purl(input = infile, output = outfile, quiet = TRUE)
  9.               └─knitr::knit(..., tangle = TRUE)
 10.                 └─knitr:::process_file(text, output)
 11.                   ├─base::withCallingHandlers(...)
 12.                   ├─knitr:::process_tangle(group)
 13.                   └─knitr:::process_tangle.block(group)
 14.                     └─base::lapply(sc_split(params$child), knit_child)
 15.                       └─knitr:::FUN(X[[i]], ...)
 16.                         └─knitr::knit(..., tangle = opts_knit$get("tangle"), envir = envir)
 17.                           └─base::readLines(input, encoding = "UTF-8", warn = FALSE)
 18.                             └─base::file(con, "r")
```

I can confirm that setting the `--no-check-coding-practices` flag works for this issue but seems a little heavy because it will skip some other checks that are helpful. Looking in the `BiocCheck::usage()` documentation, I'm not seeing any other options for skipping the child chunk check. Can we add one?

Potentially related issues: #17, #46.

Best,
Mike

**Comment by mtmorgan** [comment]
I think that the most likely path forward here will be a pull request from the community.

**Comment by mjsteinbaugh** [comment]
@mtmorgan I'll see if I can come up with something

**Comment by LiNk-NY** [comment]
See #121 
@mjsteinbaugh

**Comment by mjsteinbaugh** [comment]
Awesome thanks @LiNk-NY !
