### ISSUE TITLE
finding NEWS.md in package directory

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocCheck#56]
Hi Lori, @lshep 
It doesn't seem like `NEWS.md` is found by `BiocCheck`.

Location: https://github.com/waldronlab/SingleCellMultiModal/blob/master/NEWS.md

SPB response:
```
* Checking package NEWS...
    * NOTE: Consider adding a NEWS file, so your package news will be
      included in Bioconductor release announcements.
```

Related BiocCheck line: 

https://github.com/Bioconductor/BiocCheck/blob/1cdf169a35f874dd07f71343ab073ebff430f903/R/checks.R#L1262-L1263

Potential solution based on requirements here:
```
1.	./inst/NEWS.Rd	latex
2.	./inst/NEWS	plain text
3.	./inst/NEWS.md	mardown
4.	./NEWS.md	markdown
5.	./NEWS	plain text
```
 
```r
> apply(expand.grid(c(".", "inst"), c("NEWS.Rd", "NEWS.md", "NEWS")), 1L, paste, collapse = "/")[-1]
[1] "inst/NEWS.Rd" "./NEWS.md"    "inst/NEWS.md" "./NEWS"       "inst/NEWS"   
```

Thanks!

**Comment by lshep** [comment]
Test works when checking package untar-  but does not work on built tar.gz.  Although all the newer building CRAN packages reference having the NEWS.md in the top level directory when the package is built the tar excludes this file.  This would be consistent with what is described in 

```Note that with the exceptions of INDEX, LICENSE/LICENCE and NEWS, information files at the top level of the package will not be installed and so not be known to users of Windows and macOS compiled packages (and not seen by those who use R CMD INSTALL or install.packages on the tarball). So any information files you wish an end user to see should be included in inst. Note that if the named exceptions also occur in inst, the version in inst will be that seen in the installed package.

Things you might like to add to inst are a CITATION file for use by the citation function, and a NEWS.Rd file for use by the news function. See its help page for the specific format restrictions of the NEWS.Rd file.

**Comment by lshep** [comment]
Fixed for all valid locations in  [this commit](https://github.com/Bioconductor/BiocCheck/commit/05a2bdb2a24d792b558dd16558943cd90d4da3f3)  and removing it from the `.Rbuildignore` so it gets included in the build tar.
