### ISSUE TITLE
Single colon typos

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocCheck#60]
BiocCheck doesn't recognize typos that may happen when importing a function from a package as `package::function`. 

Example
---
Input: 
```r
matlist <- as.list(
    MultiAssayExperiment:assays(
        MultiAssayExperiment:experiments(
            MultiAssayExperiment:intersectRows(inp)
        )
    )
)
```

Output:
```
* Checking if other packages can import this one...
    * ERROR: Packages providing 1 object(s) used in this package should
      be imported in the NAMESPACE file, otherwise packages importing
      this package may fail.
    
      package::object in function()
        MultiAssayExperiment::MultiAssayExperiment in corralm()
```

**Comment by lshep** [comment]
so you think it should be more informative to inform of the typo?   I would argument that this check is doing what its suppose to if there is a typo its not guaranteed to be imported correctly right?

**Comment by LiNk-NY** [comment]
Yes, I think it would be better to suggest that they meant to type `::` instead of `:` unless when the single colon is used in an environment reference (e.g., `"package:stats"`) but that would have to be enclosed in quotes. Besides, it's preferable to load an environment using `loadNamespace` to avoid such references.

The error output doesn't make sense to me. The `NAMESPACE` file does have the lines: 
```
importFrom(MultiAssayExperiment,assays)
importFrom(MultiAssayExperiment,experiments)
importFrom(MultiAssayExperiment,intersectRows)
```
If anything, it should mention those 3 functions. You can have a look at the package here (if interested): https://github.com/Bioconductor/Contributions/issues/1492
Thanks
