### ISSUE TITLE
Author / Maintainer check

### ISSUE THREAD

**Issue by lshep** [Bioconductor/BiocCheck#61]
Force use of Authors@R  as it is internally checked by R CMD build  -   Print out ERROR if using Author:  and Maintainer:   .  While it is not strictly forbidden, it is legacy format, it is better and recommended to use Author@R .   Author and Maintainer fields can be free text and are hard to check for valid input  (email, one maintainer, etc)

**Comment by LiNk-NY** [comment]
Features WRT `Authors@R` that could be added somewhere in the documentation website (package guidelines): 
* Fine control with family names, middle names etc.
* ORCID ID as comment
* Appropriate contributor attributions

**Comment by nturaga** [comment]
Note:

Might have to be implemented in https://github.com/Bioconductor/BiocCheck/blob/master/R/BiocCheckGitClone.R. So, this is a Beginner-Intermediate stage issue.

**Comment by mtmorgan** [comment]
Sometimes contributions have Authors@R and Authors fields. I believe the later is not overwritten by the former when the package is built, so the Authors@R field is ignored. So providing both should be an error.

**Comment by lshep** [comment]
Good to know.  We already check if both are used so when updating to force Authors@R it is good to know we still have to check for this.

**Comment by grimbough** [comment]
I think it would be nice to have a validity check on an included ORCID ID.  I missed a letter in one package and it passed all checks fine, but didn't render correctly on the package landing page.

This overlaps with #80 I think
