### ISSUE TITLE
warn on use of `message(paste())`

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocCheck#64]
`message()` already pastes it's arguments, so the paste is usually (expect with `collapse=`) redundant

**Comment by lshep** [comment]
Same for `stop(paste())` and `warn(paste())`

**Comment by lcolladotor** [comment]
Though not using `paste` means that you lose the automatic space separation:

```
> stop("hola", "adios")
Error: holaadios
> stop(paste("hola", "adios"))
Error: hola adios
> x <- "bye"
> stop("hola should be", x)
Error: hola should bebye
```

**Comment by lshep** [comment]
yes but simple enough to add a space at the end and avoid the extra function call.

**Comment by lcolladotor** [comment]
I still don't see why this is an issue that amounts to a warning.

If you have multiple objects that you want to string together, I still feel like `paste()` makes it easy.

```R
> x <- "hola"
> y <- "adios"
> z <- "hello"
> message(x, y, z)
holaadioshello
> message(paste(x, y, z))
hola adios hello
> message(x, " ", y, " ", z)
hola adios hello
```

`paste0()` on the other hand, I can agree easily that it's completely redundant inside `message()` and related functions.

**Comment by lcolladotor** [comment]
Here's an example of code I would need to update https://github.com/leekgroup/recount/search?q=paste&unscoped_q=paste. Anyway, it's doable and I don't remember off the top of my head if I have `message(paste(x, y, z))` use cases.

**Comment by lshep** [comment]
It amounts to a second function call and addition to the call stack.  The paste should either be done outside the message call or not at all.

**Comment by lcolladotor** [comment]
Hm... if it's ok to do it before the `message()` call, then is this issue really about avoiding nested function calls in the same command? That would be a much more general check. I'm just trying to understand why it's a warning.

Anyway, I still think that this check can/should be implemented =) (just in case others read my messages as being negative)
