### ISSUE TITLE
warn on too-brief a Description:

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocCheck#65]
The Description should provide an abstract-like summary of the package; it would be sufficient to trigger a warning if the Description were less than 'X' characters.

**Comment by federicomarini** [comment]
What's a good lower limit for this? Happy to try to warm up the engines on this

**Comment by federicomarini** [comment]
Just thought that the threshold can actually be "data driven", and take a low-enough quantile for the distribution of all existing packages now in Bioc (I can get a sample of it by fetching the ones on my machine)

**Comment by mtmorgan** [comment]
I have a mostly up-to-date clone of all software packages
```
pkgs <- dir("~/b/git/")
fls = file.path("~/b/git/", pkgs, "/DESCRIPTION")
names(fls) <- pkgs
fls <- fls[file.exists(fls)]
words <- sapply(fls, function(fl) {
    description <- tryCatch({
        ## STAN has a merge conflict
        read.dcf(fl, "Description")
    }, error = function(e) {
        ""
    })
    lengths(strsplit(description, "[[:space:]]+"))
})
```
with
```
> quantile(words, seq(0, 1, .1))
   0%   10%   20%   30%   40%   50%   60%   70%   80%   90%  100% 
  0.0  11.0  15.0  21.0  29.0  37.0  46.0  56.0  73.6 101.0 294.0 
> words[words < 5]
           a4Base         BiocCheck           CNORode  diffGeneAnalysis 
                4                 4                 4                 3 
         genbankr            GGBase         hyperdraw IdMappingAnalysis 
                3                 1                 4                 4 
           MEIGOR        microbiome               MLP          RbcBook1 
                2                 4                 4                 4 
             Rgin       RNASeqPower             ssviz              STAN 
                4                 3                 4                 0 
> words[words > 200]
     BASiCS      biosvd    BUSpaRse       ENmix       gCMAP    gCMAPWeb 
        228         223         212         204         243         228 
 GeneAccord      goSTAG  IsoGeneGUI      kebabs MAGeCKFlute         MEB 
        248         260         276         270         205         280 
   mixOmics  MoonlightR   nanotatoR      qusage    RNAdecay     SCANVIS 
        233         215         294         202         212         236 
   seqplots     SNPhood        sscu 
        228         235         224 
> 
```

But that is 'what is' rather than 'what ought to be'. How many words to convey what a package does? At least 50?? (before doing this exercise the number in my head was '300'...).

**Comment by federicomarini** [comment]
> But that is 'what is' rather than 'what ought to be'. How many words to convey what a package does? At least 50?? (before doing this exercise the number in my head was '300'...).

Funny how we always underestimate/overestimate when we do need to do the exact opposite 😄 

My ballpark estimate (subset of course to more active package than the full clone) 

```
> quantile(wordcounts, seq(0, 1, .1))
   0%   10%   20%   30%   40%   50%   60%   70%   80%   90%  100% 
  3.0   9.0  13.0  15.0  20.0  31.0  42.0  58.5  76.0 118.0 297.0 
```

10 might be a generous value, 20 would be a good one...

<img width="689" alt="image" src="https://user-images.githubusercontent.com/7447478/82213979-5228f400-9915-11ea-87ff-0eb9ca25ba44.png">

**Comment by federicomarini** [comment]
... with a lot of orgDb/TxDB packages forming the spikes around 13-15

**Comment by mtmorgan** [comment]
Also, I think of the Description as a paragraph, and a paragraph should have a beginning, a middle, and an end. So at least three sentences... (unless we're writing fiction).

**Comment by federicomarini** [comment]
We could even articulate the check at different levels:

- too few chars: can't be, error
- too few words: meh, error/warning
- not a para: I'd be generous, and say note

**Comment by federicomarini** [comment]
Happy to start my contribution by working on this @federicomarini

**Comment by federicomarini** [comment]
Currently on it, I was trying to trigger some of the behaviors but noticed that `checkDescription` is only called by `BiocCheckGitClone` - should it also be in the classical `BiocCheck`?

Otherwise: it would make sense to perform that check "somewhere else" in the series of checks.

Happy to learn which one the recommended way would be 😉

**Comment by lshep** [comment]
I think most of the Description checks for the BiocCheck fall underneath BBScompatibility?

**Comment by federicomarini** [comment]
Yeah you're right.
Makes totally sense to move it there. Thanks @lshep !
