### ISSUE TITLE
Note:  Citation file check

### ISSUE THREAD

**Issue by lshep** [Bioconductor/BiocCheck#74]
If a citation file is present.  make sure the file can be read by R. We need to be able to call readCitationFile() on a standalone CITATION file even if the package from which the file is coming from is not installed.  The citation file would not be processed correctly and not appear on a package landing page.

**Comment by lshep** [comment]
I guess the important factor to keep in mind  in the above description is that readCitationFile needs to work without the package being installed.  That may mean the check to should in the BiocCheckGitClone that happens on the open raw git clone of a github repository before build/check installs the package?    Or maybe it doesn't matter and could go in the normal checks.R  but something to be aware of.

**Comment by federicomarini** [comment]
Can't promise to have bandwidth on this today and tomorrow, but here I'd like to elaborate on some details.

Is the `CITATION` file to be placed exclusively in the `inst` folder? Or is there some liberty in the location?

**Comment by federicomarini** [comment]
As an addon: at which point do you see fit to perform this check?

**Comment by lshep** [comment]
I could see this being part of the BBScompatiblity section or possibly its own new section.

**Comment by federicomarini** [comment]
I put together a stub of it in a separate branch of my fork - https://github.com/federicomarini/BiocCheck/tree/BCH_citationcheck_issue74

I cannot be sure to make it to the call tonight (kids 🎾 training!), but I'll make sure to wrap it up in a PR later!

**Comment by federicomarini** [comment]
Ah, I forgot. Please sign me up for this 😉  @federicomarini

**Comment by lshep** [comment]
Tested this on a package that has a currently malformatted citation file and it does not work.  (see TEQC) .  As I mentioned before BiocCheck installs the package,  the check needs to be done before the package is installed,  I think therefore this check may need to be in the BiocCheckGitClone.

**Comment by lshep** [comment]
addressed in  https://github.com/Bioconductor/BiocCheck/commit/2e82082dfb27e5cd5a3a041cfd04b5b4487bf1d7
