### ISSUE TITLE
try to detect wrong setup for non-Sweave vignettes

### ISSUE THREAD

**Issue by dtenenba** [Bioconductor/BiocCheck#9]
Example: https://tracker.bioconductor.org/issue1443
Affected tarball: https://tracker.bioconductor.org/file7436/MMDiff2_0.99.0.tar.gz

It's a knitr vignette but the DESCRIPTION file does not have the 
`VignetteBuilder: knitr` line in it.

So when BiocCheck tries to Stangle the vignette (prior to parsing its code)  it crashes because it is expecting an Sweave vignette.

However, the vignette does have a `VignetteEngine` line. So it seems like BiocCheck could detect this situation and REQUIRE that it be fixed before proceeding. It could also detect the opposite situation (VignetteBuilder line in DESCRIPTION but no VignetteEngine line in the vignette) and probably other permutations as well (no VignetteIndexEntry?).

**Comment by lshep** [comment]
Implemented in version > 1.15.7
